### ISSUE TITLE
Should not return #!eof when reading zero bytes

### ISSUE THREAD

**Issue by weinholt** [leppie/IronScheme#43] opened 2019-08-29 13:59 UTC
The procedures `get-bytevector-n`, `get-string-n`, `get-bytevector-n!` and `get-string-n!` in IronScheme don't work as expected when *count*  is zero.

All other implementations work the same way. (Except for Loko, which I'll fix). Here are the test results:

```scheme
; Guile
(get-bytevector-n (open-bytevector-input-port #vu8()) 0) => #vu8()
(get-bytevector-n (open-bytevector-input-port #vu8(1)) 0) => #vu8()
(get-string-n (open-string-input-port "") 0) => ""
(get-string-n (open-string-input-port "x") 0) => ""
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8()) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "") x 0 0)) => 0
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8(1)) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "x") x 0 0)) => 0

; Vicare
(get-bytevector-n (open-bytevector-input-port #vu8()) 0) => #vu8()
(get-bytevector-n (open-bytevector-input-port #vu8(1)) 0) => #vu8()
(get-string-n (open-string-input-port "") 0) => ""
(get-string-n (open-string-input-port "x") 0) => ""
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8()) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "") x 0 0)) => 0
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8(1)) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "x") x 0 0)) => 0

; Chez
(get-bytevector-n (open-bytevector-input-port #vu8()) 0) => #vu8()
(get-bytevector-n (open-bytevector-input-port #vu8(1)) 0) => #vu8()
(get-string-n (open-string-input-port "") 0) => ""
(get-string-n (open-string-input-port "x") 0) => ""
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8()) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "") x 0 0)) => 0
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8(1)) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "x") x 0 0)) => 0

; Larceny
(get-bytevector-n (open-bytevector-input-port #u8()) 0) => #u8()
(get-bytevector-n (open-bytevector-input-port #u8(1)) 0) => #u8()
(get-string-n (open-string-input-port "") 0) => ""
(get-string-n (open-string-input-port "x") 0) => ""
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #u8()) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "") x 0 0)) => 0
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #u8(1)) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "x") x 0 0)) => 0

; Ikarus
(get-bytevector-n (open-bytevector-input-port #vu8()) 0) => #vu8()
(get-bytevector-n (open-bytevector-input-port #vu8(1)) 0) => #vu8()
(get-string-n (open-string-input-port "") 0) => ""
(get-string-n (open-string-input-port "x") 0) => ""
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8()) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "") x 0 0)) => 0
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8(1)) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "x") x 0 0)) => 0

; Mosh
(get-bytevector-n (open-bytevector-input-port #vu8()) 0) => #vu8()
(get-bytevector-n (open-bytevector-input-port #vu8(1)) 0) => #vu8()
(get-string-n (open-string-input-port "") 0) => ""
(get-string-n (open-string-input-port "x") 0) => ""
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8()) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "") x 0 0)) => 0
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8(1)) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "x") x 0 0)) => 0

; Racket
(get-bytevector-n (open-bytevector-input-port #vu8()) 0) => #vu8()
(get-bytevector-n (open-bytevector-input-port #vu8(1)) 0) => #vu8()
(get-string-n (open-string-input-port "") 0) => ""
(get-string-n (open-string-input-port "x") 0) => ""
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8()) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "") x 0 0)) => 0
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8(1)) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "x") x 0 0)) => 0

; Ypsilon
(get-bytevector-n (open-bytevector-input-port #vu8()) 0) => #vu8()
(get-bytevector-n (open-bytevector-input-port #vu8(1)) 0) => #vu8()
(get-string-n (open-string-input-port "") 0) => ""
(get-string-n (open-string-input-port "x") 0) => ""
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8()) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "") x 0 0)) => 0
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8(1)) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "x") x 0 0)) => 0

; Sagittarius
(get-bytevector-n (open-bytevector-input-port #vu8()) 0) => #vu8()
(get-bytevector-n (open-bytevector-input-port #vu8(1)) 0) => #vu8()
(get-string-n (open-string-input-port "") 0) => ""
(get-string-n (open-string-input-port "x") 0) => ""
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8()) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "") x 0 0)) => 0
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8(1)) x 0 0)) => 0
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "x") x 0 0)) => 0

; Loko (I'll fix this, of course):
(get-bytevector-n (open-bytevector-input-port #vu8()) 0) => #!eof
(get-bytevector-n (open-bytevector-input-port #vu8(1)) 0) => #vu8()
(get-string-n (open-string-input-port "") 0) => ""
(get-string-n (open-string-input-port "x") 0) => ""
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8()) x 0 0)) => An exception has been raised, but no exception handler is installed.
The condition has 4 components:
 1. &error &serious
 2. &who
     who: eval
 3. &message
     message: "This primitive is not yet implemented"
 4. &irritants
     irritants: (get-bytevector-n!)
End of condition components.

; IronScheme
(get-bytevector-n (open-bytevector-input-port #vu8()) 0) => #<eof>
(get-bytevector-n (open-bytevector-input-port #vu8(1)) 0) => #<eof>
(get-string-n (open-string-input-port "") 0) => #<eof>
(get-string-n (open-string-input-port "x") 0) => #<eof>
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8()) x 0 0)) => #<eof>
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "") x 0 0)) => &assertion
(let ((x (make-bytevector 0))) (get-bytevector-n! (open-bytevector-input-port #vu8(1)) x 0 0)) => #<eof>
(let ((x (make-string 0))) (get-string-n! (open-string-input-port "x") x 0 0)) => &assertion

```

**Comment by leppie** [comment] 2019-08-29 15:42
Fixed in 68df2f3

Thanks

**Closed by leppie** 2019-08-29 15:42 UTC

**Comment by leppie** [comment] 2019-08-30 16:52
@weinholt Not sure if have noticed, but I am using chez-srfi now, I have committed support for IronScheme and got them merged into the 'main' repo https://github.com/arcfide/chez-srfi . 

It is also included in the default distrbution of IronScheme (my repo with some extras)

**Comment by weinholt** [comment] 2019-09-01 18:59
@leppie Yep, I saw the commits to chez-srfi. Good times.

**Comment by weinholt** [comment] 2019-09-01 19:44
@leppie Btw, if you didn't have it before, then you have it now: a SRFI-14 that supports some version of Unicode.

**Comment by leppie** [comment] 2019-09-03 11:34
@weinholt the problem is not unicode, it is the string representation in .NET which is UTF16 and uses surrogate pairs in strings for anything out of range. I cant use it like that as it will break some string requirements from scheme, and cant really rewrite strings, as it will be incompatible and slow :(
